FROM clearlinux:latest AS builder

# Install a minimal versioned OS into /install_root, and bundled tools if any
ENV CLEAR_VERSION=43250
RUN swupd os-install --no-progress --no-boot-update --no-scripts \
    --version ${CLEAR_VERSION} \
    --path /install_root \
    --statedir /swupd-state \
    --bundles os-core-update,which,git,c-basic,wget,java-basic,devpkg-Linux-PAM,\
unzip,nodejs-basic


# Download and install conda into /usr/bin
ENV MINICONDA_VERSION=py38_23.11.0-2
RUN swupd bundle-add --no-progress curl && \
    curl -sL https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -o /tmp/miniconda.sh && \
    sh /tmp/miniconda.sh -bfp /usr


# Use conda to install remaining tools/dependencies into /usr/local
ENV VEP_VERSION=102.0 \
    HTSLIB_VERSION=1.10.2 \
    BCFTOOLS_VERSION=1.10.2 \
    SAMTOOLS_VERSION=1.10 \
    LIFTOVER_VERSION=377
    
RUN conda create -qy -p /usr/local \
    -c conda-forge \
    -c bioconda \
    -c defaults \
    mamba 
    
RUN mamba install -qy -p /usr/local \
    -c conda-forge \
    -c bioconda \
    -c defaults \
    snakemake \
    r-base

#generate ca-certificate in order to go git clones
#RUN clrtrust generate



#RUN pip install matplot


################################################
# installation layer
########################
# Deploy the minimal OS and tools into a clean target layer
FROM scratch AS installer

LABEL maintainer="Cyriac Kandoth <ckandoth@gmail.com>"

COPY --from=builder /install_root /
COPY --from=builder /usr/local /usr/local

#copy the ca certificate that is used to authentication of true web for git
COPY --from=builder /var/cache/ca-certs/anchors/ /var/cache/ca-certs/anchors/


#COPY data /opt/data
#COPY *.pl /opt/
WORKDIR /opt

#Adding users
ARG UID=1000
ARG GID=1000
ARG USER1=user1

#for env variable used by 
ARG arch="x86_64"


#create a new user. this is necessary to make the file generated in docker to 
# have the permission (read/write) to the host
RUN groupadd --gid $GID $USER1 && useradd --uid $UID --gid $GID $USER1

RUN curl -sL https://github.com/rstudio/rstudio/archive/refs/tags/v2024.12.1+563.tar.gz \
-o /tmp/rstudio.tar.gz  
RUN cd /tmp && mkdir rstudio && tar -zxvf ./rstudio.tar.gz -C rstudio --strip-components=1 

RUN cd /tmp/rstudio/dependencies/linux && ./install-boost 
RUN cd /tmp/rstudio/dependencies/common && ./install-soci && ./install-dictionaries  

RUN cd /tmp/rstudio/dependencies/common && ./install-mathjax && ./install-quarto

# define a new bash function, since it is defined in clearlinux but is called in the rstudio installation
# need to define and call it in the same process. (need to figure it out how to do it globally)
RUN arch(){ echo "x86_64"; };  arch && export -f arch && cd /tmp/rstudio/dependencies/common && ./install-cef && \
        ./install-pandoc && \
        ./install-sentry-cli && \
        ./install-npm-dependencies && \
        #./install-crashpad && 
        ./install-panmirror && \
        ./install-sccache && \
        ./install-yarn && \
        ./install-yaml-cpp

RUN cd /tmp/rstudio && mkdir build  
RUN touch /etc/os-release
RUN cd /tmp/rstudio/build && \ 
    cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=R

RUN cd /tmp/rstudio/build && make install

####################
#builder 2
###################
FROM clearlinux:latest AS builder2

# Install a minimal versioned OS into /install_root, and bundled tools if any
ENV CLEAR_VERSION=43250
RUN swupd os-install --no-progress --no-boot-update --no-scripts \
    --version ${CLEAR_VERSION} \
    --path /install_root \
    --statedir /swupd-state \
    --bundles os-core-update
    
###############################
### final layer
#######################
# Deploy the minimal OS and tools into a clean target layer
FROM scratch

LABEL maintainer="Cyriac Kandoth <ckandoth@gmail.com>"

COPY --from=builder2 /install_root /
COPY --from=installer /usr/local /usr/local

#copy the ca certificate that is used to authentication of true web for git
COPY --from=builder /var/cache/ca-certs/anchors/ /var/cache/ca-certs/anchors/


#COPY data /opt/data
#COPY *.pl /opt/
WORKDIR /opt

#Adding users
ARG UID=1000
ARG GID=1000
ARG USER1=user1


#create a new user. this is necessary to make the file generated in docker to 
# have the permission (read/write) to the host
RUN groupadd --gid $GID $USER1 && useradd --uid $UID --gid $GID $USER1


USER user1
WORKDIR /home/${USER1}/vep 
#note this one is the project folder, holding snakemake files

#make three folders, first for project data, second for reference



RUN mkdir -p seq_data
RUN mkdir -p ref_seq

USER 0

# to run
## docker run -it --rm vep2 su - user1 

# to compile/build
## docker build -f Dockerfile . -t vep2

## for language server, this is the facility for providing IDE like environment
#       for different languages. 
# 1) first install necessary language server such as jupyterlab-lsp python-language-server
#    Note: jupyterlab-lsp is necessary for all language servers,
#           here we are interested in python language servers
# 2) need to enable/activate the installed servers
#       open jupyterlab and then => settings ==> setting editor
#               => plugin manager 
#           then enable or activate specific servers
#

# a few things to note/to do LATER:
# 1) this has not been done yet. It has only successfully (?) preconfigured.
# and installed. need to make it run 
#  we don't want to spend time on this, since it is too large in size.
# 3) need to test the running of the server (it can be run)
# 4) also need to configure the server.

# rstudio, can be preconfigured to build for server or desktop version.

# ##this one is try to reduce the size by adding one extra intermediate layer.
# it does, but not reduce too much. still big. 6G.
