FROM rocker/rstudio:4.3.1
#create a folder in container and entering it.
#something it is not working well at the root directory.
WORKDIR /home/rstudio/jupyter_renv
#note about directory, we use the bind volume to the container volum main

RUN sudo apt-get update && apt-get install -y --no-install-recommends libxt6 \
    && apt-get install -y libz-dev sudo \
    && apt-get install -y libfontconfig1-dev \
    && apt-get install -y libfribidi-dev \
    && apt-get install -y libfreetype6-dev libtiff5-dev libjpeg-dev \
    && apt-get install -y --no-install-recommends libxml2-dev libtcl8.6 tcl8.6 tcl8.6-dev libtk8.6 tk8.6 tk8.6-dev

RUN apt-get update -qq && apt-get -y --no-install-recommends install cmake pandoc libpng-dev libgsl0-dev make libssl-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libfontconfig1-dev python3 libcurl4-openssl-dev libglu1-mesa-dev libgl1-mesa-dev zlib1g-dev libgmp3-dev libmpfr-dev libicu-dev

RUN R -e "install.packages('renv', repos = c(CRAN = 'https://cloud.r-project.org'))"

# approach two
# to set up the 
COPY renv.lock renv.lock
#COPY renv.lock /home/renv.lock
RUN  mkdir -p renv

COPY .Rprofile .Rprofile
COPY renv/activate.R renv/activate.R
COPY renv/settings.json renv/settings.json
#COPY renv/settings.dcf renv/settings.dcf

COPY *.ipynb ./
COPY subfolder ./subfolder
COPY READ* ./
COPY *.R ./
COPY DESCRIPTION ./


# Note for above, we don't have renv/settings.json somehow (?),
# it is not necessary!!! we could just need .Rprofile and activate.R and renv.lock
#

#change owner ship to rstudio, RECURSIVELY with -R
# and then restor the renv library as the user "rstudio"
RUN chown -R rstudio . \
    && sudo -u rstudio R -e "renv::settings\$use.cache(FALSE);renv::restore()"
#RUN chown rstudio /home/renv.lock

RUN sudo -u rstudio echo "setwd(\"/home/rstudio/jupyter_renv/\")" > /home/rstudio/.Rprofile

RUN sudo -u rstudio echo "renv::load()" >> /home/rstudio/.Rprofile 
#    && echo ".rs.restartR()" >>/home/rstudio/.Rprofile 


