FROM continuumio/miniconda3:23.10.0-1

#here we define the newly created user
# this is necessary since it will be used by the docker compse 
# at run time to solve the file permission issues.
# UID/GID/ruser are all arbitrary. 
# we call it ruser to be a general name for easily used purpose
# UID and GID will be modified at the run time (in yaml compose file)
# depending on who is calling it.
ARG UID=2000
ARG GID=2000
ARG USER1=user1

#create a new user. this is necessary to make the file generated in docker to 
# have the permission (read/write) to the host
RUN addgroup --gid $GID $USER1 
RUN adduser --uid $UID --gid $GID --gecos '' --disabled-password $USER1

#Start doing conda 
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget sudo libncurses5 libxt6 libxmu6 unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


#create a folder in container and entering it.
#something it is not working well at the root directory.
WORKDIR /home/${USER1}/cnvkit  

#this is have root permission, since at this point, it is under root!!! 
# you need to be careful if you want to avoid it.!!! move it to after the 
# user1 role to start working. see below.

# Install miniconda
# ref : https://fabiorosado.dev/blog/install-conda-in-docker/
ENV CONDA_DIR=/opt/conda

#RUN echo "$PATH"

#--- RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && 
#---    /bin/bash ~/miniconda.sh -b -p ~/miniconda3

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH 


##COPY environment.yml environment.yml
## COPY r_requirements_install*.R ./
RUN conda init
RUN conda create -n cnvkit -v



SHELL ["/bin/bash", "-c"]

#
RUN source ${CONDA_DIR}/etc/profile.d/conda.sh \
    && conda activate cnvkit && conda config --add channels defaults \
    && conda config --add channels bioconda \
    && conda config --add channels conda-forge \
    && conda install -y mamba && mamba install -y cnvkit=0.9.10 \
    && mamba install -y r-base \
    && Rscript -e "install.packages('BiocManager',dependencies=TRUE, repos='http://cran.rstudio.com/');BiocManager::install('DNAcopy')"
    
# create another env for snakemake separately.
COPY environment_snakemake.yaml environment_snakemake.yaml
RUN conda env create -f environment_snakemake.yaml -v -n snakemake
 


# set up as user role. and everything down after will be user permission.
#   it can not directly write to WORKING DIR since it is under the root permission.
#               (see above). need to be careful about the permission
#   now we CANNOT write/make a new folder at ~/cnvkit/, since it was created by root.
#           if we want, we have more that part to after using new user1 role.

USER ${USER1}
RUN mkdir -p ~/project #this is the one mapped to the real project with scripts related to projects at run time, say snakemake for example.
RUN mkdir -p ~/data #this is again mapped to data. this is separated only because the data are huge and stored on somewhere different 
COPY README* ./


   
#install Gistic2 program
RUN mkdir -p ~/Gistic2

ADD GISTIC_2_0_23.tar.gz /home/${USER1}/Gistic2

USER root  
#here we run as root, because otherwise the unzip is not going to work. the trouble
#came because the GISTIC_2_0_23.tar.gz is labelled with other user permission
# if we don't do root, we will not be able to unzip it. weird!! 

#USER ${USER1}
RUN  unzip -q /home/${USER1}/Gistic2/MCR_Installer/MCRInstaller.zip -d /home/${USER1}/Gistic2/MCR_Installer \
    && /home/${USER1}/Gistic2/MCR_Installer/install -mode silent -agreeToLicense yes -destinationFolder /home/${USER1}/Gistic2/MATLAB_Compiler_Runtime



#change back to root, otherwise we will have trouble to 
# do things like change file owners (in yaml at the run time)
USER root



